package MakonFM::Model::DB;

use Moose;
use namespace::autoclean;
BEGIN { extends 'Catalyst::Model::DBIC::Schema' }

__PACKAGE__->config(
    schema_class => 'MakonFM::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=MakonFM',
        user => 'sixtease',
        password => '',
    }
);

sub get_version {
    my ($self, $key) = @_;
    my $rs = $self->resultset('Version')->find($key);
    return $rs ? $rs->value : 0
}

1

__END__

1

__END__

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MakonFM::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.49

=cut
