package MakonFM::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'MakonFM::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=MakonFM',
        user => 'sixtease',
        password => '',
    }
);

=head1 NAME

MakonFM::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<MakonFM>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MakonFM::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.49

=head1 AUTHOR

Jan Oldrich Kruza <sixtease@cpan.org>

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
